### ISSUE TITLE
Add `customMetricTypeDomains` to `signalfx.gcp.Integration`

### ISSUE THREAD

**Issue by Moon1706** [pulumi/pulumi-signalfx#178]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As you can see from header, I'm going to use `customMetricTypeDomains`, but this field just absents in this module, but exists in [the official docs](https://dev.splunk.com/observability/docs/integrations/gcp_integration_overview/).
If I've understood correctly how this module is working, I have to add this new feature to the Terraform module [splunk-terrafrom/signalfx](https://registry.terraform.io/providers/splunk-terraform/signalfx/latest/docs/resources/gcp_integration). But to be honestly, I'm a newcomer in editing Pulumi modules, so I'll be grateful for any hint.

### Affected area/feature

Pulumi resource and data source `signalfx.gcp.Integration`

**Comment by Moon1706** [comment]
https://github.com/splunk-terraform/terraform-provider-signalfx/issues/411

**Comment by guineveresaenger** [comment]
hi @Moon1706 - thank you for filing the upstream enhancement request! We'll pull in the changes as soon as upstream includes them.

**Comment by Moon1706** [comment]
@guineveresaenger 
Terraform provider was updated. Please keep me posted your changes)

**Comment by Moon1706** [comment]
@guineveresaenger 
ping

**Comment by AaronFriel** [comment]
Hey @Moon1706, sorry for not getting back to you. It looks like this was added last month on Feb 8, in v5.8.0 and newer. Please give that at try, and if you find that there's an issue using this field please raise a new issue!
